# -*- coding: utf-8 -*-
"""Anamoly_in_Space.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucmyYPgZ7Pjl4hJM8YZhJBh1RCDptjBK
"""

import pandas as pd

df = pd.read_csv("segments.csv")
df.head()

df.describe()

df.info()

df['timestamp'] = pd.to_datetime(df['timestamp'])

df = df.sort_values(['channel', 'segment', 'timestamp'])

df['anomaly'].value_counts()

df['anomaly'].value_counts(normalize=True)

import matplotlib.pyplot as plt

sample_segment = df[df['segment'] == df['segment'].iloc[0]]

plt.plot(sample_segment['timestamp'], sample_segment['value'])
plt.title("Sample Telemetry Signal")
plt.show()

normal = df[df['anomaly'] == 0].iloc[:500]
anomaly = df[df['anomaly'] == 1].iloc[:500]

plt.plot(normal['value'], label='Normal')
plt.plot(anomaly['value'], label='Anomaly')
plt.legend()
plt.show()

lengths = df.groupby('segment').size()

print(lengths.describe())

df = df[['channel', 'segment', 'timestamp', 'value', 'anomaly']]

df['channel'] = df['channel'].astype('category').cat.codes



grouped = df.groupby('segment')

sequences = []
labels = []

for _, group in grouped:
    seq = group[['value']].values
    label = group['anomaly'].iloc[0]

    sequences.append(seq)
    labels.append(label)

print(len(sequences))
print(len(labels))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    sequences, labels, test_size=0.25, random_state=42, stratify=labels
)

X_train

max_len = max([len(seq) for seq in sequences])
print(max_len)



MAX_LEN = 200   # or 150–300 range

!pip install tensorflow
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences


X_train_pad = pad_sequences(X_train, maxlen=MAX_LEN, padding='post', truncating='post')
X_test_pad  = pad_sequences(X_test, maxlen=MAX_LEN, padding='post', truncating='post')

X_train_pad = X_train_pad.reshape(X_train_pad.shape[0], X_train_pad.shape[1], 1)
X_test_pad  = X_test_pad.reshape(X_test_pad.shape[0], X_test_pad.shape[1], 1)

import numpy as np

y_train = np.array(y_train)
y_test  = np.array(y_test)

print(X_train_pad.shape)
print(X_test_pad.shape)

from sklearn.preprocessing import StandardScaler
import numpy as np

scaler = StandardScaler()

# X_train and X_test are lists, so reshape() cannot be called on them directly.
# Scaling should be applied to the padded sequences, X_train_pad and X_test_pad.

# Store original shapes to reshape back after scaling
original_shape_train = X_train_pad.shape
original_shape_test = X_test_pad.shape

# Flatten the 3D padded arrays to 2D for the StandardScaler
X_train_2d = X_train_pad.reshape(-1, 1)
X_test_2d = X_test_pad.reshape(-1, 1)

# Fit the scaler on the training data and transform both train and test data
X_train_scaled_2d = scaler.fit_transform(X_train_2d)
X_test_scaled_2d = scaler.transform(X_test_2d)

# Reshape the scaled 2D arrays back to their original 3D shape for the LSTM model
X_train_pad = X_train_scaled_2d.reshape(original_shape_train)
X_test_pad = X_test_scaled_2d.reshape(original_shape_test)

from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights = dict(enumerate(class_weights))
print(class_weights)

X_train_flat = X_train_pad.reshape(X_train_pad.shape[0], -1)
X_test_flat  = X_test_pad.reshape(X_test_pad.shape[0], -1)

from sklearn.ensemble import IsolationForest

iso_model = IsolationForest(
    n_estimators=100,
    contamination=0.1,   # adjust later
    random_state=42
)

iso_model.fit(X_train_flat)

y_pred_train = iso_model.predict(X_train_flat)
y_pred_test  = iso_model.predict(X_test_flat)

import numpy as np

y_pred_test = np.where(y_pred_test == 1, 0, 1)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_test))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_test)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("Isolation Forest Confusion Matrix")
plt.show()

X_train_flat = X_train_pad.reshape(X_train_pad.shape[0], -1)
X_test_flat  = X_test_pad.reshape(X_test_pad.shape[0], -1)

X_train_normal = X_train_flat[y_train == 0]

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_train_flat.shape[1]

input_layer = Input(shape=(input_dim,))

encoded = Dense(128, activation='relu')(input_layer)
encoded = Dense(64, activation='relu')(encoded)
encoded = Dense(32, activation='relu')(encoded)

decoded = Dense(64, activation='relu')(encoded)
decoded = Dense(128, activation='relu')(decoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)

autoencoder.compile(optimizer='adam', loss='mse')

history = autoencoder.fit(
    X_train_normal, X_train_normal,
    epochs=50,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

import numpy as np

X_test_pred = autoencoder.predict(X_test_flat)

mse = np.mean(np.power(X_test_flat - X_test_pred, 2), axis=1)

threshold = np.percentile(mse, 70)
print("Threshold:", threshold)

y_pred_ae = (mse > threshold).astype(int)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_ae))

import matplotlib.pyplot as plt

plt.hist(mse, bins=50)
plt.axvline(threshold, color='r')
plt.title("Reconstruction Error Distribution")
plt.show()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Bidirectional, Dense, Dropout

model = Sequential([
    Bidirectional(LSTM(128, return_sequences=True), input_shape=(MAX_LEN, 1)),
    Dropout(0.3),

    Bidirectional(LSTM(64)),
    Dropout(0.3),

    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

model.fit(
    X_train_pad, y_train,
    epochs=30,
    batch_size=64,
    validation_split=0.1,
    class_weight={0:1, 1:8},
    callbacks=[early_stop]
)

y_pred_prob = model.predict(X_test_pad)

# 1. Get probabilities
y_pred_prob = model.predict(X_test_pad)

# 2. Apply threshold (VERY IMPORTANT)
threshold = 0.6
y_pred_lstm = (y_pred_prob > threshold).astype(int)

# 3. Flatten
y_pred_lstm = y_pred_lstm.flatten()

# 4. Evaluation
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_lstm))

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_lstm))

y_pred_lstm = (y_pred_prob > 0.6).astype(int)

import matplotlib.pyplot as plt

plt.plot(history.history['loss'], label='train')
plt.plot(history.history['val_loss'], label='val')
plt.legend()
plt.title("Training Loss")
plt.show()

for t in [0.3, 0.4, 0.5, 0.6]:
    y_pred = (y_pred_prob > t).astype(int)

    print(f"\nThreshold {t}")
    print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt

plt.hist(y_pred_prob, bins=50)
plt.title("Prediction Probability Distribution")
plt.show()

from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_pred_prob)

plt.plot(thresholds, recall[:-1], label='Recall')
plt.plot(thresholds, precision[:-1], label='Precision')
plt.legend()
plt.xlabel("Threshold")
plt.show()

from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_pred_prob)

import matplotlib.pyplot as plt

plt.plot(thresholds, precision[:-1], label='Precision')
plt.plot(thresholds, recall[:-1], label='Recall')
plt.legend()
plt.xlabel("Threshold")
plt.title("Precision vs Recall")
plt.show()

# -*- coding: utf-8 -*-
"""Anamoly_in_Space.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ucmyYPgZ7Pjl4hJM8YZhJBh1RCDptjBK
"""

import pandas as pd

df = pd.read_csv("segments.csv")
df.head()

df.describe()

df.info()

df['timestamp'] = pd.to_datetime(df['timestamp'])

df = df.sort_values(['channel', 'segment', 'timestamp'])

df['anomaly'].value_counts()

df['anomaly'].value_counts(normalize=True)

import matplotlib.pyplot as plt

sample_segment = df[df['segment'] == df['segment'].iloc[0]]

plt.plot(sample_segment['timestamp'], sample_segment['value'])
plt.title("Sample Telemetry Signal")
plt.show()

normal = df[df['anomaly'] == 0].iloc[:500]
anomaly = df[df['anomaly'] == 1].iloc[:500]

plt.plot(normal['value'], label='Normal')
plt.plot(anomaly['value'], label='Anomaly')
plt.legend()
plt.show()

lengths = df.groupby('segment').size()

print(lengths.describe())

df = df[['channel', 'segment', 'timestamp', 'value', 'anomaly']]

df['channel'] = df['channel'].astype('category').cat.codes



grouped = df.groupby('segment')

sequences = []
labels = []

for _, group in grouped:
    seq = group[['value']].values
    label = group['anomaly'].iloc[0]

    sequences.append(seq)
    labels.append(label)

print(len(sequences))
print(len(labels))

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    sequences, labels, test_size=0.25, random_state=42, stratify=labels
)

X_train

max_len = max([len(seq) for seq in sequences])
print(max_len)



MAX_LEN = 200   # or 150–300 range

!pip install tensorflow
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences


X_train_pad = pad_sequences(X_train, maxlen=MAX_LEN, padding='post', truncating='post')
X_test_pad  = pad_sequences(X_test, maxlen=MAX_LEN, padding='post', truncating='post')

X_train_pad = X_train_pad.reshape(X_train_pad.shape[0], X_train_pad.shape[1], 1)
X_test_pad  = X_test_pad.reshape(X_test_pad.shape[0], X_test_pad.shape[1], 1)

import numpy as np

y_train = np.array(y_train)
y_test  = np.array(y_test)

print(X_train_pad.shape)
print(X_test_pad.shape)

from sklearn.preprocessing import StandardScaler
import numpy as np

scaler = StandardScaler()

# X_train and X_test are lists, so reshape() cannot be called on them directly.
# Scaling should be applied to the padded sequences, X_train_pad and X_test_pad.

# Store original shapes to reshape back after scaling
original_shape_train = X_train_pad.shape
original_shape_test = X_test_pad.shape

# Flatten the 3D padded arrays to 2D for the StandardScaler
X_train_2d = X_train_pad.reshape(-1, 1)
X_test_2d = X_test_pad.reshape(-1, 1)

# Fit the scaler on the training data and transform both train and test data
X_train_scaled_2d = scaler.fit_transform(X_train_2d)
X_test_scaled_2d = scaler.transform(X_test_2d)

# Reshape the scaled 2D arrays back to their original 3D shape for the LSTM model
X_train_pad = X_train_scaled_2d.reshape(original_shape_train)
X_test_pad = X_test_scaled_2d.reshape(original_shape_test)

from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights = dict(enumerate(class_weights))
print(class_weights)

X_train_flat = X_train_pad.reshape(X_train_pad.shape[0], -1)
X_test_flat  = X_test_pad.reshape(X_test_pad.shape[0], -1)

from sklearn.ensemble import IsolationForest

iso_model = IsolationForest(
    n_estimators=100,
    contamination=0.1,   # adjust later
    random_state=42
)

iso_model.fit(X_train_flat)

y_pred_train = iso_model.predict(X_train_flat)
y_pred_test  = iso_model.predict(X_test_flat)

import numpy as np

y_pred_test = np.where(y_pred_test == 1, 0, 1)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_test))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_test)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("Isolation Forest Confusion Matrix")
plt.show()

X_train_flat = X_train_pad.reshape(X_train_pad.shape[0], -1)
X_test_flat  = X_test_pad.reshape(X_test_pad.shape[0], -1)

X_train_normal = X_train_flat[y_train == 0]

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_train_flat.shape[1]

input_layer = Input(shape=(input_dim,))

encoded = Dense(128, activation='relu')(input_layer)
encoded = Dense(64, activation='relu')(encoded)
encoded = Dense(32, activation='relu')(encoded)

decoded = Dense(64, activation='relu')(encoded)
decoded = Dense(128, activation='relu')(decoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)

autoencoder.compile(optimizer='adam', loss='mse')

history = autoencoder.fit(
    X_train_normal, X_train_normal,
    epochs=50,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

import numpy as np

X_test_pred = autoencoder.predict(X_test_flat)

mse = np.mean(np.power(X_test_flat - X_test_pred, 2), axis=1)

threshold = np.percentile(mse, 70)
print("Threshold:", threshold)

y_pred_ae = (mse > threshold).astype(int)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_ae))

import matplotlib.pyplot as plt

plt.hist(mse, bins=50)
plt.axvline(threshold, color='r')
plt.title("Reconstruction Error Distribution")
plt.show()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Bidirectional, Dense, Dropout

model = Sequential([
    Bidirectional(LSTM(128, return_sequences=True), input_shape=(MAX_LEN, 1)),
    Dropout(0.3),

    Bidirectional(LSTM(64)),
    Dropout(0.3),

    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

model.fit(
    X_train_pad, y_train,
    epochs=30,
    batch_size=64,
    validation_split=0.1,
    class_weight={0:1, 1:8},
    callbacks=[early_stop]
)

y_pred_prob = model.predict(X_test_pad)

# 1. Get probabilities
y_pred_prob = model.predict(X_test_pad)

# 2. Apply threshold (VERY IMPORTANT)
threshold = 0.6
y_pred_lstm = (y_pred_prob > threshold).astype(int)

# 3. Flatten
y_pred_lstm = y_pred_lstm.flatten()

# 4. Evaluation
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_lstm))

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_lstm))

y_pred_lstm = (y_pred_prob > 0.6).astype(int)

import matplotlib.pyplot as plt

plt.plot(history.history['loss'], label='train')
plt.plot(history.history['val_loss'], label='val')
plt.legend()
plt.title("Training Loss")
plt.show()

for t in [0.3, 0.4, 0.5, 0.6]:
    y_pred = (y_pred_prob > t).astype(int)

    print(f"\nThreshold {t}")
    print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt

plt.hist(y_pred_prob, bins=50)
plt.title("Prediction Probability Distribution")
plt.show()

from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_pred_prob)

plt.plot(thresholds, recall[:-1], label='Recall')
plt.plot(thresholds, precision[:-1], label='Precision')
plt.legend()
plt.xlabel("Threshold")
plt.show()

from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_pred_prob)

import matplotlib.pyplot as plt

plt.plot(thresholds, precision[:-1], label='Precision')
plt.plot(thresholds, recall[:-1], label='Recall')
plt.legend()
plt.xlabel("Threshold")
plt.title("Precision vs Recall")
plt.show()





